### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/js-classes#1]
https://github.com/DenisPitsul/js-classes/blob/ab907bd6fcbb560ade74eab29fce117b79cf49db/assets/js/task1.js#L22
- та сама підступна помилка) Якщо не протестувати роботу всіх методів, то можна цього не побачити

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/js-classes/commit/9e9ba3faa84342e3fb70ae6d7163bd5d985166cb
